---
title: "GSVA Analysis"
output: html_document
date: "July 10, 2025"
---


```{r setup}

rm(list=ls())

library(DESeq2)
library(edgeR)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
library(writexl)
library(pheatmap)
library(RColorBrewer)
library(clusterProfiler)
library(GSVA)
color =  colorRampPalette(c("cyan", "black", "yellow"))(n = 7)

```

## Genesets 

```{r}
gset  = read.gmt("~/hsiehlab/MAIN_DATA/lee_lab_rnaseq_GSE225013/gene_sets_symbol_5.gmt")
lst= split(gset, gset[,1])
lst = lapply(lst, function(x) {
  goi = x[,2]
  rm_idx = which(goi=="")
  if(length(rm_idx)!=0){
    goi = goi[-rm_idx]
  }
  goi
})
sig = list( "BASAL-6-SIG" = c("FGFBP1", "TP63", "TRIM29", "ITGB4"), 
            "BASAL-PAM50-SIG" = c("FGFBP1",
                                  "TP63",  "TRIM29", "ITGB4", "PTTG1",
                                  "CDC20","ORC6L",  "KIF2C", "UBE2C",
                                  "MELK", "BIRC5", "NUF2", "CEP55",
                                  "EXO1", "CENPF", "NDC80", "TYMS",
                                  "UBE2T", "ANLN", "CCNB1", "RRM2", "MKI67"), 
            "LUMINAL-6-SIG" = c("AR", "KLK3",   "NKX3-1", "TMPRSS2", "AMARCR",
                                "SPINK1",  "FOLH1"), 
            "LUMINAL-PAM50-SIG" = c("ESR1", "PGR", "BCL2", "FOXA1",
                                    "CDC6", "CXXC5", "MLPH", "MAPT",
                                    "NAT1", "MDM2", "MMP11", "BLVRA"))

lst = c(lst, sig)
lst[[1]] = c("AR", lst[[1]])
```

## GSVA analysis  of cell lines. 

```{r}
df = read.delim("RAW_COUNTS_PCDT_LUCAP_summary_data_RM_v1.txt", header=T, 
                stringsAsFactors=FALSE, row.names=2, check.names=FALSE)
rawdata = df[, grep("35CS_FBS|176_FBS|35CR_FBS", colnames(df))]

cpm_counts= log2( cpm(rawdata) +1)
gsvapar <- gsvaParam(cpm_counts, lst, maxDiff=TRUE)
res <- gsva(gsvapar) 

mydf = cbind(rowMeans( res[, 1:2]), rowMeans(res[, 3:4]), rowMeans( res[, 5:8]) )
colnames(mydf) = c("35CS", "35CR", "176")
mydf = t(mydf)
mydf = as.data.frame(mydf)

avg_mat= cbind(rowMeans( cpm_counts[, 1:2]), rowMeans(cpm_counts[, 3:4]), rowMeans( cpm_counts[, 5:8]) )
colnames(avg_mat) = c("35CS", "35CR", "176")


 mydf$phenotype = c("AR+/NE-", "AR+/NE-", "ARlow/NE-")
 ann_colors = list(
     phenotype = c("AR+/NE-"="darkgreen",  "ARlow/NE-"="purple"))
goi = c("AR", "KLK3", "NKX3-1", "TMPRSS2", "SYP", "CHGA", "NKX2-1", "SCG3" )

pdf("fig_cell_lines_gsva.pdf", width =5, height = 5)
 pheatmap(avg_mat[goi,] , scale = "row" , cluster_rows = F, 
          colorRampPalette(c("blue", "black", "yellow"))(75),
          cluster_cols = FALSE, 
          annotation_col = mydf[, c("phenotype","ARG.6", "NE.6"), drop=FALSE], 
          annotation_colors = ann_colors)
 dev.off()
```

## GSVA analysis for PDX models. 

```{r}
df = as.data.frame(read_xlsx("Fig.5-PDXmodel/.xlsx", sheet = 3))
df2 = df[c(17:30), c(5:9)]
rownames(df2) = df[,3]
colnames(df2) = df[15, 5:9]

gsvapar <- gsvaParam(df2, lst[c(2:4)], maxDiff=TRUE)
res2 <- gsva(gsvapar) 

avg_mat= cbind(rowMeans( df2[, 1:3]), rowMeans(df2[, 4:5]) )
colnames(avg_mat) = c("35CS",  "176")

mydf = cbind(rowMeans( res2[, 1:3]), rowMeans(res[, 4:5]))
colnames(mydf) = c("35CS", "176")
mydf = t(mydf)
mydf = as.data.frame(mydf)
mydf$phenotype = c("AR+/NE-", "ARlow/NE-")

goi = c("FGFBP1", "TP63", "TRIM29", "ITGB4", "KRT14")

ann_colors = list(
    phenotype = c("AR+/NE-"="darkgreen",  "ARlow/NE-"="purple"))

pdf("fig_pdx_gsva.pdf", width =5, height = 5)
pheatmap(avg_mat[goi,] , scale = "row" , cluster_rows = F, 
         colorRampPalette(c("blue", "black", "yellow"))(75),
         cluster_cols = FALSE, 
         annotation_col = mydf[, c("phenotype","ARG.6", "NE.6"), drop=FALSE], 
         annotation_colors = ann_colors)
dev.off()
```
